name = "AugmentedGaussianProcesses"
uuid = "38eea1fd-7d7d-5162-9d08-f89d0f2e271e"
authors = ["Theo Galy-Fajou <theo.galyfajou@gmail.com>"]
version = "0.11.5"

[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPLikelihoods = "6031954c-0455-49d7-b3b9-3e1c99afaf40"
InducingPoints = "b4bd816d-b975-4295-ac05-5f2992945579"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractMCMC = "2, 3, 4"
ChainRulesCore = "1"
Distributions = "0.21.5, 0.22, 0.23, 0.24, 0.25"
FastGaussQuadrature = "0.4"
ForwardDiff = "0.10"
GPLikelihoods = "0.2, 0.3, 0.4"
InducingPoints = "0.2, 0.3"
KernelFunctions = "0.8, 0.9, 0.10"
Optimisers = "0.2"
ProgressMeter = "1"
RecipesBase = "1.0, 1.1"
Reexport = "0.2, 1"
SimpleTraits = "0.9"
SpecialFunctions = "1, 2"
StatsBase = "0.32, 0.33"
StatsFuns = "0.9, 1"
Zygote = "0.6.7"
julia = "1.6"
